spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri

logging.level.org.springframework.boot.context.config=DEBUG

logging.level.me.paulschwarz.springdotenv=TRACE